config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	#match ':controller(/:action(/:id))(.:format)'
	#match ':controller/:action/(:id)', via: :get
	get 'players/index'
	
	resources :players do
		get :click
		get :buy_1
		get :buy_2
		get :buy_3
		get :buy_4
		get :buy_5
		get :buy_6
		get :buy_7
		get :buy_8
		get :buy_9
		get :buy_10
	end
	
	root 'players#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
	
	validates :dna, numericality: { greater_than_or_equal_to: 0, allow_nil: false}
	validates :name, presence: true
	validates :level, numericality: { greater_than_or_equal_to: 0, allow_nil: false}
	validates :level2, numericality: { greater_than_or_equal_to: 0, allow_nil: false}
	validates :level3, numericality: { greater_than_or_equal_to: 0, allow_nil: false}
	validates :level4, numericality: { greater_than_or_equal_to: 0, allow_nil: false}
	validates :level5, numericality: { greater_than_or_equal_to: 0, allow_nil: false}
	validates :level6, numericality: { greater_than_or_equal_to: 0, allow_nil: false}
	validates :level7, numericality: { greater_than_or_equal_to: 0, allow_nil: false}
	validates :level8, numericality: { greater_than_or_equal_to: 0, allow_nil: false}
	validates :level9, numericality: { greater_than_or_equal_to: 0, allow_nil: false}
	validates :level10, numericality: { greater_than_or_equal_to: 0, allow_nil: false}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

	before_action :find_player, only: [:show, :edit, :update, :destroy]	

	
	def index
		@players = Player.all
	end	

	# /player/id GET
	def show
		unless @player
			render html: "Page not found", status: 404
		end
	end
	
	#/player/new GET
	def new
		@player = Player.new
	end
	
	#/player/id/edit GET
	def edit
	end
	
	#/player POST
	def create
		@player = Player.find_or_create_by(player_params)
		if @player.errors.empty?
			redirect_to player_path(@player) #/players/id
		else
			render "new"
		end
	end

	# /player/id PUT пост со спец полем
	def update
	@player.update_attributes(player_params)
		if @player.errors.empty?
			redirect_to player_path(@player) #/players/id
		else
			render "edit"
		end
	end

	# /player/id DELETE post со спец полем
	def destroy
		@player.destroy
		redirect_to action: "index"
	end

	def click
		@player = Player.find(params[:player_id])
		click_get_dna = 1 + @player.level + @player.level2 * 5 + @player.level3 * 50 + @player.level4 * 90 + @player.level5 * 300 + @player.level6 * 500 + @player.level7 * 850 + @player.level8 * 1200 + @player.level9 * 30000 + @player.level10 * 999999
		@player.update_attributes(dna: @player.dna + click_get_dna, lifetime_dna: @player.lifetime_dna + click_get_dna)
		redirect_to @player
	end

	def buy_1
		@player = Player.find(params[:player_id])
		if @player.dna >= @player.level_cost
			@player.update_attributes(level: @player.level + 1, dna: @player.dna - @player.level_cost, level_cost: @player.level_cost * 1.2)
		end
		redirect_to @player
	end

	def buy_2
		@player = Player.find(params[:player_id])
		if @player.dna >= @player.level2_cost
			@player.update_attributes(level2: @player.level2 + 1, dna: @player.dna - @player.level2_cost, level2_cost: @player.level2_cost * 1.1)
		end
		redirect_to @player
	end

	def buy_3
		@player = Player.find(params[:player_id])
		if @player.dna >= @player.level3_cost
			@player.update_attributes(level3: @player.level3 + 1, dna: @player.dna - @player.level3_cost, level3_cost: @player.level3_cost * 1.1)
		end
		redirect_to @player
	end

	def buy_4
		@player = Player.find(params[:player_id])
		if @player.dna >= @player.level4_cost
			@player.update_attributes(level4: @player.level4 + 1, dna: @player.dna - @player.level4_cost, level4_cost: @player.level4_cost * 1.2)
		end
		redirect_to @player
	end

	def buy_5
		@player = Player.find(params[:player_id])
		if @player.dna >= @player.level5_cost
			@player.update_attributes(level5: @player.level5 + 1, dna: @player.dna - @player.level5_cost, level5_cost: @player.level5_cost * 1.1)
		end
		redirect_to @player
	end

	def buy_6
		@player = Player.find(params[:player_id])
		if @player.dna >= @player.level6_cost
			@player.update_attributes(level6: @player.level6 + 1, dna: @player.dna - @player.level6_cost, level6_cost: @player.level6_cost * 1.2)
		end
		redirect_to @player
	end

		def buy_7
		@player = Player.find(params[:player_id])
		if @player.dna >= @player.level7_cost
			@player.update_attributes(level7: @player.level7 + 1, dna: @player.dna - @player.level7_cost, level7_cost: @player.level7_cost * 1.2)
		end
		redirect_to @player
	end

	def buy_8
		@player = Player.find(params[:player_id])
		if @player.dna >= @player.level8_cost
			@player.update_attributes(level8: @player.level8 + 1, dna: @player.dna - @player.level8_cost, level8_cost: @player.level8_cost * 1.2)
		end
		redirect_to @player
	end

	def buy_9
		@player = Player.find(params[:player_id])
		if @player.dna >= @player.level9_cost
			@player.update_attributes(level9: @player.level9 + 1, dna: @player.dna - @player.level9_cost, level9_cost: @player.level9_cost * 1.2)
		end
		redirect_to @player
	end

	def buy_10
		@player = Player.find(params[:player_id])
		if @player.dna >= @player.level10_cost
			@player.update_attributes(level10: @player.level10 + 1, dna: @player.dna - @player.level10_cost, level10_cost: @player.level10_cost * 1.2)
		end
		redirect_to @player
	end

private
		
	def find_player
		@player = Player.find(params[:id])
	end
	
  def player_params
    allow = [:name, :level, :dna]
    params.require(:player).permit(allow)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kurs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/edit.html.erb
<center>
<p class="main_name"> <%= link_to image_tag('main_name.png') %> </p>
<h1>Обновление</h1>

<%= form_for @player do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name, class: "reg" %>
  </p>
	<p>
    <%= form.label :dna	 %><br>
    <%= form.text_field :dna, class: "reg" %>
  </p>

  <p>
    <%= form.submit class: "btn btn-success" %>
  </p>
<% end %>
</center>

app/views/players/index.html.erb
<center>
<p class="main_name"> <%= link_to image_tag('main_name.png') %> </p>
</center>


<div class="container-fluid">
 <div class="row">
  <div class="col-xs-3">
		<center>		
		<table border="1">
		<%  sorted_players = @players.sort_by { |h | h[:lifetime_dna] }.reverse %>
		ТОП Игроков
		<tr>
			<th>Ник</th>
			<th>ДНК за все время</th>
		</tr>
		<% sorted_players.each do |i| %>
		<tr>
			<td><%=  i.name %></td>
			<td><%= i.lifetime_dna %></td>
		</tr>
		<% end %>
		</table>
		</center>
	</div>
  <div class="col-xs-6"><%= link_to image_tag('reg.png', :height => '200px'), new_player_url%></div>
  <div class="col-xs-3"></div>
 </div>
</div>

app/views/players/new.html.erb
<center>
<p class="main_name"> <%= link_to image_tag('main_name.png') %> </p>
<h1>Регистрация/Вход</h1>

</centr>


<%= form_for @player do |form| %>
  <p>

    <%= form.text_field :name, placeholder: 'Введите имя', class: "reg" %>
  </p>
  <p>
    <%= form.submit class: "btn btn-success" %>
  </p>
<% end %>

app/views/players/show.html.erb
<center>
<p class="main_name"> <%= link_to image_tag('main_name.png') %> </p>
<h2>Player: <%= @player.name %></h2>
<h3>ДНК: <%= @player.dna %></h3>
</center>

<div class="container-fluid">
   <div class="row">
    <div class="col-xs-5">
		
			<div class="row">
				<div class="col-xs-3"> <%= image_tag('upgrade1.png', :height => '85px') %> <p class="name_upgrade">Бактерия (+1 ДНК к клику)</p></div>
				<div class="col-xs-3"> <p>Куплено</p> <p class="upgrade_first">x<%= @player.level%> </p> </div>
				<div class="col-xs-3"> <p>Стоимость</p> <p class="upgrade_first"><%= @player.level_cost %> ДНК</p> </div>
				<div class="col-xs-3"> <p class="upgrade"><%= button_to "Buy", player_buy_1_url(@player), :class => "btn btn-success", :method => :get %></p> 				</div>
			</div>

			<div class="row">
				<div class="col-xs-3"> <%= image_tag('upgrade2.jpg', :height => '85px') %> <p class="name_upgrade">Многоклеточные (+5 ДНК к клику)</p></div>
				<div class="col-xs-3"> <p class="upgrade">x<%= @player.level2%> </p> </div>
				<div class="col-xs-3"> <p class="upgrade"><%= @player.level2_cost %> ДНК</p> </div>
				<div class="col-xs-3"> <p class="upgrade"><%= button_to "Buy", player_buy_2_url(@player), :class => "btn btn-success", :method => :get %></p> 				</div>
			</div>

			<div class="row">
				<div class="col-xs-3"> <%= image_tag('upgrade3.png', :height => '85px') %> <p class="name_upgrade">Рыба (+50 ДНК к клику)</p></div>
				<div class="col-xs-3"> <p class="upgrade">x<%= @player.level3%> </p> </div>
				<div class="col-xs-3"> <p class="upgrade"><%= @player.level3_cost %> ДНК</p> </div>
				<div class="col-xs-3"> <p class="upgrade"><%= button_to "Buy", player_buy_3_url(@player), :class => "btn btn-success", :method => :get %></p> 				</div>
			</div>

			<div class="row">
				<div class="col-xs-3"> <%= image_tag('upgrade4.png', :height => '85px') %> <p class="name_upgrade">Рептилия (+90 ДНК к клику)</p></div>
				<div class="col-xs-3"> <p class="upgrade">x<%= @player.level4%> </p> </div>
				<div class="col-xs-3"> <p class="upgrade"><%= @player.level4_cost %> ДНК</p> </div>
				<div class="col-xs-3"> <p class="upgrade"><%= button_to "Buy", player_buy_4_url(@player), :class => "btn btn-success", :method => :get %></p> 				</div>
			</div>

			<div class="row">
				<div class="col-xs-3"> <%= image_tag('upgrade5.png', :height => '85px') %> <p class="name_upgrade">Млекопитающие (+300 ДНК к клику)</p></div>
				<div class="col-xs-3"> <p class="upgrade">x<%= @player.level5%> </p> </div>
				<div class="col-xs-3"> <p class="upgrade"><%= @player.level5_cost %> ДНК</p> </div>
				<div class="col-xs-3"> <p class="upgrade"><%= button_to "Buy", player_buy_5_url(@player), :class => "btn btn-success", :method => :get %></p> 				</div>
			</div>

		</div>
    <div class="col-xs-2"><%= link_to image_tag('1.png', :height => '200px'), player_click_url(@player) %>
		<br>
ДНК за клик: <%= 1 + @player.level + @player.level2 * 5 + @player.level3 * 50 + @player.level4 * 90 + @player.level5 * 300 + @player.level6 * 500 + @player.level7 * 850 + @player.level8 * 1200 + @player.level9 * 30000 + @player.level10 * 999999 %>
<p><%= button_to "Выйти", players_index_url, :class => "btn btn-warning", :method => :get %></p>
		</div>
    <div class="col-xs-5">
		
			<div class="row">
				<div class="col-xs-3"> <%= image_tag('upgrade6.png', :height => '85px') %> <p class="name_upgrade">Приматы (+500 ДНК к клику)</p></div>
				<div class="col-xs-3"> <p>Куплено</p> <p class="upgrade_first">x<%= @player.level6%> </p> </div>
				<div class="col-xs-3"> <p>Стоимость</p> <p class="upgrade_first"><%= @player.level6_cost %> ДНК</p> </div>
				<div class="col-xs-3"> <p class="upgrade"><%= button_to "Buy", player_buy_6_url(@player), :class => "btn btn-success", :method => :get %></p> 				</div>
			</div>

			<div class="row">
				<div class="col-xs-3"> <%= image_tag('upgrade7.jpeg', :height => '85px') %> <p class="name_upgrade">Неандерталец (+850 ДНК к клику)</p></div>
				<div class="col-xs-3"> <p class="upgrade">x<%= @player.level7%> </p> </div>
				<div class="col-xs-3"> <p class="upgrade"><%= @player.level7_cost %> ДНК</p> </div>
				<div class="col-xs-3"> <p class="upgrade"><%= button_to "Buy", player_buy_7_url(@player), :class => "btn btn-success", :method => :get %></p> 				</div>
			</div>

			<div class="row">
				<div class="col-xs-3"> <%= image_tag('upgrade8.png', :height => '85px') %> <p class="name_upgrade">Человек разумный (+1200 ДНК к клику)</p></div>
				<div class="col-xs-3"> <p class="upgrade">x<%= @player.level8%> </p> </div>
				<div class="col-xs-3"> <p class="upgrade"><%= @player.level8_cost %> ДНК</p> </div>
				<div class="col-xs-3"> <p class="upgrade"><%= button_to "Buy", player_buy_8_url(@player), :class => "btn btn-success", :method => :get %></p> 				</div>
			</div>

			<div class="row">
				<div class="col-xs-3"> <%= image_tag('upgrade9.jpg', :height => '85px') %> <p class="name_upgrade">Сверхчеловек (+30000 ДНК к клику)</p></div>
				<div class="col-xs-3"> <p class="upgrade">x<%= @player.level9%> </p> </div>
				<div class="col-xs-3"> <p class="upgrade"><%= @player.level9_cost %> ДНК</p> </div>
				<div class="col-xs-3"> <p class="upgrade"><%= button_to "Buy", player_buy_9_url(@player), :class => "btn btn-success", :method => :get %></p> 				</div>
			</div>

			<div class="row">
				<div class="col-xs-3"> <%= image_tag('upgrade10.jpg', :height => '85px') %> <p class="name_upgrade">СВЕРХРАЗУМ!!11! (+999999 ДНК к клику)</p></div>
				<div class="col-xs-3"> <p class="upgrade">x<%= @player.level10%> </p> </div>
				<div class="col-xs-3"> <p class="upgrade"><%= @player.level10_cost %> ДНК</p> </div>
				<div class="col-xs-3"> <p class="upgrade"><%= button_to "Buy", player_buy_10_url(@player), :class => "btn btn-success", :method => :get %></p> 				</div>
			</div>

		</div>
   </div>
  </div>


<div>Собрано ДНК за все время: <%= @player.lifetime_dna %></div>
<div>Дата регистрации: <%= @player.created_at %></div>
<div class="exit"><%= button_to "Удалить", @player, method: :delete, data: {confirm: "Точно удалить сохранение?"}, :class => "btn btn-danger"%></div>